version: '3.8'

services:
  maik-bank-pg-server:
    image: postgres:15-alpine
    container_name: maik-bank-pg-server

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - maik-bank-postgres_data:/var/lib/postgresql/data

  maik-bank-redis-server:
    image: redis:7-alpine
    container_name: maik-bank-redis-server
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - maik-bank-redis_data:/data

volumes:
  maik-bank-postgres_data:
  maik-bank-redis_data:
