export enum KEY_OF_INJECTION {
  USER_REPOSITORY = 'USER_REPOSITORY',
  ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY',
}

export enum ROLE {
  USER = 'USER',
  ADMIN = 'ADMIN',
}

export enum ACCOUNT_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
